name       : lolcat
version    : 100.0.0
release    : 6
source     :
    - https://rubygems.org/downloads/lolcat-100.0.0.gem : da5b40d7bffa8b3f2e77de5ab945be0bc3231ced630b5c9b4c58e6cb6014354c
license    : BSD-3-Clause
component  : programming.ruby
summary    : Rainbows and unicorns!
description: |
    Lolcat is an utility which concatenates like similar to cat command and adds rainbow coloring to it. Lolcat is primarily used for rainbow coloring of text in Linux Terminal.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby-manpages
    - ruby-optimist
    - ruby-paint
install    : |
    %gem_install

    #cleaning
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/gems/lolcat-100.0.0/{.gitignore,LICENSE,README.md,ass,lolcat.gemspec,Gemfile,Rakefile}
    rm -rf $installdir/usr/lib64/ruby/gems/2.6.0/{build_info,doc,extensions,specifications}

    # Installing manual entry for lolcat
    tar xf data.tar.gz
    install -Dm00644 man/lolcat.6 -t $installdir/usr/share/man/man6
