name       : lolcat
version    : 99.9.11
release    : 2
source     :
    - https://rubygems.org/downloads/lolcat-99.9.11.gem : 97572243637f8ccc0c40241819f6a69ebb438646228effb216150ba9491912fc
license    : BSD-3-Clause
component  : programming.ruby
summary    : Rainbows and unicorns!
description: |
    Lolcat is an utility which concatenates like similar to cat command and adds rainbow coloring to it. Lolcat is primarily used for rainbow coloring of text in Linux Terminal.
builddeps  :
    - pkgconfig(ruby-2.6)
    - ruby-manpages
    - ruby-paint
    - ruby-trollop
rundeps    :
    - ruby-manpages
    - ruby-paint
    - ruby-trollop
install    : |
    %gem_install
